//! Build script for `trove-app`.
//!
//! Embeds the upstream gpui-kit themes *without* vendoring copies into this
//! repo. Those JSON files live only in the gpui-kit git checkout — the
//! compiled crate does not ship them — so we ask `cargo metadata` where the
//! gpui-kit source actually is (correct across the local git cache, CI and
//! vendored source trees alike), copy every theme into `OUT_DIR`, and emit an
//! include list that `app/theme.rs` pulls in.
//!
//! `TROVE_THEMES_DIR` overrides the lookup with an explicit path to a
//! `themes/` directory, as an escape hatch.
//!
//! Only `std` is used: adding a build-dependency could re-resolve the lockfile
//! and move the pinned gpui-kit revision, so the `cargo metadata` JSON is
//! scanned for `manifest_path` values instead of being parsed with serde.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

fn main() {
    println!("cargo:rerun-if-env-changed=TROVE_THEMES_DIR");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let mut generated = String::from(
        "// @generated by build.rs — upstream gpui-kit themes embedded at build time.\n\
         pub(super) static BUILTIN_THEME_JSON: &[&str] = &[\n",
    );

    match locate_themes_dir() {
        Some(dir) => {
            let dest = out.join("themes");
            fs::create_dir_all(&dest).expect("create OUT_DIR/themes");
            for stem in theme_stems(&dir) {
                let src = dir.join(format!("{stem}.json"));
                let Ok(json) = fs::read_to_string(&src) else {
                    continue;
                };
                fs::write(dest.join(format!("{stem}.json")), json).expect("write theme");
                writeln!(
                    generated,
                    "    include_str!(concat!(env!(\"OUT_DIR\"), \"/themes/{stem}.json\")),"
                )
                .expect("writing to a String cannot fail");
                println!("cargo:rerun-if-changed={}", src.display());
            }
        }
        // Not fatal: the two framework default themes are always available, so
        // a missing catalogue only shrinks the picker.
        None => println!(
            "cargo:warning=could not locate the gpui-kit themes dir; only the default themes \
             will be selectable (set TROVE_THEMES_DIR to point at a themes/ directory)"
        ),
    }

    generated.push_str("];\n");
    fs::write(out.join("builtin_themes.rs"), generated).expect("write builtin_themes.rs");
}

/// Find the gpui-kit `themes/` directory: an explicit override first, else the
/// dependency's real source location as reported by `cargo metadata`.
fn locate_themes_dir() -> Option<PathBuf> {
    if let Some(dir) = env::var_os("TROVE_THEMES_DIR") {
        return Some(PathBuf::from(dir));
    }

    let metadata = cargo_metadata()?;
    // The themes sit at the checkout root, next to (not inside) the gpui-kit
    // crate, so walk up from its manifest until a populated `themes/` appears.
    for manifest in manifest_paths(&metadata).filter(|p| p.contains("gpui-kit")) {
        for ancestor in Path::new(manifest).ancestors() {
            let themes = ancestor.join("themes");
            if themes.join("catppuccin.json").is_file() {
                return Some(themes);
            }
        }
    }
    None
}

/// Run `cargo metadata` (locked, so it never mutates `Cargo.lock`) and return
/// its JSON stdout.
fn cargo_metadata() -> Option<String> {
    println!("cargo:rerun-if-changed=../../Cargo.lock");
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .args(["metadata", "--format-version=1", "--locked"])
        .current_dir(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .output()
        .ok()?;
    output
        .status
        .success()
        .then(|| String::from_utf8(output.stdout).ok())?
}

/// Yield every `manifest_path` string value in the metadata JSON. Paths on the
/// platforms that build the GUI contain no characters JSON would escape, so a
/// direct scan is enough and avoids a serde build-dependency.
fn manifest_paths(json: &str) -> impl Iterator<Item = &str> {
    const KEY: &str = "\"manifest_path\":\"";
    json.match_indices(KEY).filter_map(|(i, _)| {
        let rest = &json[i + KEY.len()..];
        rest.find('"').map(|end| &rest[..end])
    })
}

/// Every `<stem>.json` in `dir`, sorted so the embedded order — and therefore
/// the picker's — is stable across machines.
fn theme_stems(dir: &Path) -> Vec<String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut stems: Vec<String> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .filter_map(|path| {
            path.file_stem()
                .map(|stem| stem.to_string_lossy().into_owned())
        })
        .collect();
    stems.sort();
    stems
}
